name: Deploy

on:
  push:
    branches:
      - source
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.1'
        bundler-cache: true
    - name: Install deps
      run: |
        npm ci
    - name: Build site
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        READ_TOKEN: ${{ secrets.READ_TOKEN }}
      run: |
        npm run tinacms build && bundle exec jekyll build
   - name: Build TinaCMS
  env:
    TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
    TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  run: npx tinacms build
      with:
        folder: _site
